[build]

[target.wasm32-unknown-unknown]
rustflags = [
    '-Ctarget-feature=-atomics,+simd128',
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    '-Ctarget-cpu=native',
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    '-Ctarget-cpu=native',
]

[target.x86_64-apple-darwin]
rustflags = [
    '-Ctarget-cpu=native',
]
